import type{AgentEnv,Source}from'./client-types';
import{clean,now}from'./client-utils';
import{googleFetch,gmailText,sheetText}from'./client-google-content';
const words=['cuestionario','check-in','seguimiento','formulario','analítica','analitica','informe','trainingpeaks','nutrición','nutricion','fueling','lesión','lesion','dolor','competición','competicion','carrera','fatiga','sueño','sueno','digestivo','adherencia','plan semanal'];
const relevant=(s:string)=>words.some(k=>s.toLowerCase().includes(k));
async function token(e:AgentEnv){const b=new URLSearchParams({client_id:e.GOOGLE_CLIENT_ID||'',client_secret:e.GOOGLE_CLIENT_SECRET||'',refresh_token:e.GOOGLE_REFRESH_TOKEN||'',grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:b});if(!r.ok)throw new Error(`Google OAuth ${r.status}`);const j=await r.json<any>();if(!j.access_token)throw new Error('Google OAuth sin token');return String(j.access_token)}
const head=(a:any[],n:string)=>a?.find(x=>String(x.name).toLowerCase()===n.toLowerCase())?.value||'';
export async function sources(e:AgentEnv,since:Date){const t=await token(e),out:Source[]=[],user=encodeURIComponent(e.GOOGLE_USER||'me'),q=encodeURIComponent(`${e.GMAIL_QUERY||'label:"APD/Entrada Cliente"'} after:${Math.floor(since.getTime()/1000)}`),lr=await googleFetch(t,`https://gmail.googleapis.com/gmail/v1/users/${user}/messages?maxResults=50&q=${q}`),lj=await lr.json<any>();for(const x of lj.messages||[]){const r=await googleFetch(t,`https://gmail.googleapis.com/gmail/v1/users/${user}/messages/${x.id}?format=full`),m=await r.json<any>(),title=head(m.payload?.headers,'subject')||'Sin asunto',names:string[]=[],content=await gmailText(t,x.id,m.payload,names),text=clean(`${title} ${content} Adjuntos: ${names.join(', ')}`);if(!relevant(text))continue;const from=head(m.payload?.headers,'from');out.push({sourceType:'GMAIL',id:x.id,revision:String(m.historyId||''),modifiedAt:new Date(Number(m.internalDate||Date.now())).toISOString(),title,text,mimeType:'message/rfc822',clientSeed:from||x.id,metadata:{threadId:m.threadId,attachmentNames:names}})}const folder=e.GOOGLE_INBOX_FOLDER_ID;if(folder){const dq=encodeURIComponent(`'${folder}' in parents and modifiedTime > '${since.toISOString()}' and trashed = false`),dr=await googleFetch(t,`https://www.googleapis.com/drive/v3/files?pageSize=100&orderBy=modifiedTime&q=${dq}&fields=files(id,name,mimeType,modifiedTime,version,description,webViewLink,parents)`),dj=await dr.json<any>();for(const f of dj.files||[]){let content='';if(f.mimeType==='application/vnd.google-apps.document')content=await(await googleFetch(t,`https://www.googleapis.com/drive/v3/files/${f.id}/export?mimeType=text%2Fplain`)).text();else if(f.mimeType==='application/vnd.google-apps.spreadsheet')content=await sheetText(t,String(f.id));else if(String(f.mimeType).startsWith('text/')||/application\/(json|csv|xml)/i.test(String(f.mimeType)))content=await(await googleFetch(t,`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`)).text();else content=`Archivo para revisión manual. Tipo ${f.mimeType}`;const title=String(f.name||'Archivo'),text=clean(`${title} ${f.description||''} ${content}`);if(!relevant(text))continue;out.push({sourceType:'DRIVE',id:String(f.id),revision:String(f.version||f.modifiedTime||''),modifiedAt:String(f.modifiedTime||now()),title,text,mimeType:String(f.mimeType||''),clientSeed:title,metadata:{webViewLink:f.webViewLink,parents:f.parents}})}}return{token:t,items:out}}
export async function createDoc(e:AgentEnv,t:string,title:string,content:string){const r=await googleFetch(t,'https://www.googleapis.com/drive/v3/files?fields=id,webViewLink',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:title,mimeType:'application/vnd.google-apps.document',parents:[e.GOOGLE_DRAFTS_FOLDER_ID]})}),f=await r.json<any>();await googleFetch(t,`https://docs.googleapis.com/v1/documents/${f.id}:batchUpdate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requests:[{insertText:{location:{index:1},text:content}}]})});return{id:String(f.id),url:String(f.webViewLink||`https://docs.google.com/document/d/${f.id}/edit`)}}
