import type{AgentEnv,Source}from'./client-types';import{clean,now}from'./client-utils';
const words=['cuestionario','check-in','seguimiento','formulario','analítica','analitica','informe','trainingpeaks','nutrición','nutricion','fueling','lesión','lesion','dolor','competición','competicion','carrera','fatiga','sueño','sueno','digestivo','adherencia','plan semanal'];
const relevant=(s:string)=>words.some(k=>s.toLowerCase().includes(k));
async function token(e:AgentEnv){const b=new URLSearchParams({client_id:e.GOOGLE_CLIENT_ID||'',client_secret:e.GOOGLE_CLIENT_SECRET||'',refresh_token:e.GOOGLE_REFRESH_TOKEN||'',grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:b});if(!r.ok)throw new Error(`Google OAuth ${r.status}`);const j=await r.json<any>();if(!j.access_token)throw new Error('Google OAuth sin token');return String(j.access_token)}
async function api(t:string,u:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('authorization',`Bearer ${t}`);const r=await fetch(u,{...init,headers:h});if(!r.ok)throw new Error(`Google API ${r.status}: ${await r.text()}`);return r}
const decode=(s:string)=>{const n=s.replace(/-/g,'+').replace(/_/g,'/'),p=n+'='.repeat((4-n.length%4)%4);return new TextDecoder().decode(Uint8Array.from(atob(p),c=>c.charCodeAt(0)))};
const head=(a:any[],n:string)=>a?.find(x=>String(x.name).toLowerCase()===n)?.value||'';
function body(p:any):string{let x=p?.body?.data?decode(p.body.data):'';for(const c of p?.parts||[])x+=' '+body(c);return clean(x.replace(/<[^>]+>/g,' '))}
export async function sources(e:AgentEnv,since:Date){const t=await token(e),out:Source[]=[];const user=encodeURIComponent(e.GOOGLE_USER||'me'),q=encodeURIComponent(`${e.GMAIL_QUERY||'label:"APD/Entrada Cliente"'} after:${Math.floor(since.getTime()/1000)}`),lr=await api(t,`https://gmail.googleapis.com/gmail/v1/users/${user}/messages?maxResults=50&q=${q}`),lj=await lr.json<any>();for(const x of lj.messages||[]){const r=await api(t,`https://gmail.googleapis.com/gmail/v1/users/${user}/messages/${x.id}?format=full`),m=await r.json<any>(),title=head(m.payload?.headers,'subject')||'Sin asunto',text=clean(`${title} ${body(m.payload)}`);if(!relevant(text))continue;const from=head(m.payload?.headers,'from');out.push({sourceType:'GMAIL',id:x.id,revision:String(m.historyId||''),modifiedAt:new Date(Number(m.internalDate||Date.now())).toISOString(),title,text,mimeType:'message/rfc822',clientSeed:from||x.id,metadata:{threadId:m.threadId}})}
const folder=e.GOOGLE_INBOX_FOLDER_ID;if(folder){const dq=encodeURIComponent(`'${folder}' in parents and modifiedTime > '${since.toISOString()}' and trashed = false`),dr=await api(t,`https://www.googleapis.com/drive/v3/files?pageSize=100&orderBy=modifiedTime&q=${dq}&fields=files(id,name,mimeType,modifiedTime,version,description,webViewLink,parents)`),dj=await dr.json<any>();for(const f of dj.files||[]){let content='';if(f.mimeType==='application/vnd.google-apps.document')content=await(await api(t,`https://www.googleapis.com/drive/v3/files/${f.id}/export?mimeType=text%2Fplain`)).text();else if(String(f.mimeType).startsWith('text/'))content=await(await api(t,`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`)).text();else content=`Archivo para revisión manual. Tipo ${f.mimeType}`;const title=String(f.name||'Archivo'),text=clean(`${title} ${f.description||''} ${content}`);if(!relevant(text))continue;out.push({sourceType:'DRIVE',id:String(f.id),revision:String(f.version||f.modifiedTime||''),modifiedAt:String(f.modifiedTime||now()),title,text,mimeType:String(f.mimeType||''),clientSeed:title,metadata:{webViewLink:f.webViewLink,parents:f.parents}})}}return{token:t,items:out}}
export async function createDoc(e:AgentEnv,t:string,title:string,content:string){const r=await api(t,'https://www.googleapis.com/drive/v3/files?fields=id,webViewLink',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:title,mimeType:'application/vnd.google-apps.document',parents:[e.GOOGLE_DRAFTS_FOLDER_ID]})}),f=await r.json<any>();await api(t,`https://docs.googleapis.com/v1/documents/${f.id}:batchUpdate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requests:[{insertText:{location:{index:1},text:content}}]})});return{id:String(f.id),url:String(f.webViewLink||`https://docs.google.com/document/d/${f.id}/edit`)}}