interface Env {
  DB: D1Database;
  AI: any;
  DRY_RUN: string;
  GOOGLE_USER: string;
  GOOGLE_DRAFTS_FOLDER_ID: string;
  SLACK_CHANNEL_ID: string;
  NOTION_DATA_SOURCE_ID: string;
  NOTION_VERSION: string;
  AI_MODEL: string;
  MAX_ITEMS_PER_RUN: string;
  MAX_SOURCE_CHARS: string;
  LOOKBACK_MINUTES: string;
  MAX_AI_CALLS_PER_DAY: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_REFRESH_TOKEN: string;
  SLACK_BOT_TOKEN: string;
  SLACK_SIGNING_SECRET: string;
  NOTION_TOKEN: string;
  ADMIN_TOKEN: string;
}

type SourceType = 'GMAIL' | 'DRIVE';
type Decision = 'APROBADO' | 'REVISAR' | 'POSPUESTO' | 'DESCARTADO';
type SourceDoc = { sourceType: SourceType; id: string; revision: string; modifiedAt: string; title: string; text: string; mimeType: string; clientSeed: string; metadata: Record<string, unknown> };
type Analysis = { material_type: string; objective: string; summary: string; changes: string[]; improved: string[]; worsened: string[]; maintained: string[]; red_flags: string[]; pending_questions: string[]; hypotheses: string[]; training: string[]; nutrition_fueling: string[]; recovery: string[]; metrics: string[]; reply_message: string; priority_score_0_100: number; review_points: string[]; minutes_saved: number };

const enc = new TextEncoder();
const KEYWORDS = ['cuestionario','check-in','check in','seguimiento','formulario','analítica','analitica','informe','trainingpeaks','nutrición','nutricion','fueling','lesión','lesion','dolor','competición','competicion','carrera','fatiga','sueño','sueno','digestivo','adherencia','plan semanal'];
const REACTIONS: Record<string, Decision> = { white_check_mark:'APROBADO', repeat:'REVISAR', arrows_counterclockwise:'REVISAR', pause_button:'POSPUESTO', double_vertical_bar:'POSPUESTO', x:'DESCARTADO', heavy_multiplication_x:'DESCARTADO' };

const now = () => new Date().toISOString();
const int = (v: string | undefined, d: number) => Number.isFinite(parseInt(v ?? '', 10)) ? parseInt(v ?? '', 10) : d;
const bool = (v: string | undefined, d = false) => v == null ? d : v.toLowerCase() === 'true';
const out = (data: unknown, status = 200) => new Response(JSON.stringify(data), { status, headers: { 'content-type':'application/json; charset=utf-8' } });
const relevant = (s: string) => KEYWORDS.some(k => s.toLocaleLowerCase('es-ES').includes(k));
const clean = (s: string) => s.replace(/\u0000/g,'').replace(/\s+/g,' ').trim();
const redact = (s: string) => s.replace(/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b/g,'[EMAIL REDACTADO]').replace(/\b(?:\+34\s*)?[6789]\d{8}\b/g,'[TELÉFONO REDACTADO]').replace(/\b\d{8}[A-Z]\b/gi,'[DOCUMENTO REDACTADO]').replace(/\b\d{2,3}(?:[.,]\d+)?\s?kg\b/gi,'[PESO REDACTADO]');

async function sha(s: string) { const d = await crypto.subtle.digest('SHA-256', enc.encode(s)); return [...new Uint8Array(d)].map(x => x.toString(16).padStart(2,'0')).join(''); }
function equal(a: string, b: string) { if (a.length !== b.length) return false; let d = 0; for (let i=0;i<a.length;i++) d |= a.charCodeAt(i)^b.charCodeAt(i); return d===0; }
function b64url(s: string) { const n=s.replace(/-/g,'+').replace(/_/g,'/'); const p=n+'='.repeat((4-n.length%4)%4); const bin=atob(p); return new TextDecoder().decode(Uint8Array.from(bin,c=>c.charCodeAt(0))); }
function htmlToText(s: string) { return clean(s.replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&')); }
function arr(v: unknown) { return Array.isArray(v) ? v.map(x=>clean(String(x))).filter(Boolean).slice(0,12) : []; }

async function accessToken(env: Env) {
  const body = new URLSearchParams({ client_id:env.GOOGLE_CLIENT_ID, client_secret:env.GOOGLE_CLIENT_SECRET, refresh_token:env.GOOGLE_REFRESH_TOKEN, grant_type:'refresh_token' });
  const r = await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});
  if (!r.ok) throw new Error(`Google OAuth ${r.status}: ${await r.text()}`);
  const j = await r.json<{access_token?:string}>(); if (!j.access_token) throw new Error('Google OAuth sin access_token'); return j.access_token;
}
async function gjson<T>(token: string, url: string, init: RequestInit = {}) { const h=new Headers(init.headers); h.set('authorization',`Bearer ${token}`); const r=await fetch(url,{...init,headers:h}); if(!r.ok) throw new Error(`Google API ${r.status}: ${await r.text()}`); return r.json<T>(); }
async function gtext(token: string, url: string) { const r=await fetch(url,{headers:{authorization:`Bearer ${token}`}}); if(!r.ok) throw new Error(`Google API ${r.status}: ${await r.text()}`); return r.text(); }
const header=(hs:any[]|undefined,n:string)=>hs?.find(h=>String(h.name).toLowerCase()===n.toLowerCase())?.value??'';

async function partText(token:string,messageId:string,p:any,names:string[]):Promise<string>{ let t=''; const m=String(p?.mimeType??''), f=String(p?.filename??''); if(f) names.push(f); if(p?.body?.data&&(m==='text/plain'||m==='text/html')){const d=b64url(p.body.data);t+=m==='text/html'?htmlToText(d):d;} if(p?.body?.attachmentId&&f&&/^(text\/|application\/(json|csv|xml))/i.test(m)){const a=await gjson<{data?:string}>(token,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(messageId)}/attachments/${encodeURIComponent(p.body.attachmentId)}`);if(a.data)t+=`\nAdjunto ${f}:\n${b64url(a.data)}`;} for(const c of p?.parts??[])t+=`\n${await partText(token,messageId,c,names)}`; return t; }

async function gmail(env:Env,token:string,since:Date){ const q=encodeURIComponent(`after:${Math.floor(since.getTime()/1000)}`); const l=await gjson<any>(token,`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(env.GOOGLE_USER||'me')}/messages?maxResults=50&q=${q}`); const res:SourceDoc[]=[]; for(const x of l.messages??[]){const m=await gjson<any>(token,`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(env.GOOGLE_USER||'me')}/messages/${encodeURIComponent(x.id)}?format=full`);const subject=header(m.payload?.headers,'subject')||'Sin asunto',from=header(m.payload?.headers,'from');const names:string[]=[];let body=m.payload?.body?.data?b64url(m.payload.body.data):'';body+=await partText(token,x.id,m.payload,names);const text=clean(`${subject}\n${body}\nAdjuntos: ${names.join(', ')}`);if(!relevant(text))continue;const email=from.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)?.[0]?.toLowerCase()??x.id;res.push({sourceType:'GMAIL',id:x.id,revision:String(m.historyId??''),modifiedAt:new Date(Number(m.internalDate??Date.now())).toISOString(),title:subject,text,mimeType:'message/rfc822',clientSeed:email,metadata:{threadId:m.threadId,attachmentNames:names}});} return res; }

async function sheet(token:string,id:string){const meta=await gjson<any>(token,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}?fields=sheets.properties.title`);const titles=(meta.sheets??[]).slice(0,8).map((s:any)=>String(s.properties?.title??'')).filter(Boolean);if(!titles.length)return'';const qs=titles.map((t:string)=>`ranges=${encodeURIComponent(`'${t.replace(/'/g,"''")}'!A1:Z200`)}`).join('&');const v=await gjson<any>(token,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values:batchGet?majorDimension=ROWS&${qs}`);return(v.valueRanges??[]).map((r:any)=>`${r.range??'Hoja'}\n${(r.values??[]).map((row:any[])=>row.map(c=>String(c??'')).join(' | ')).join('\n')}`).join('\n\n');}
async function driveContent(token:string,f:any){const id=String(f.id),m=String(f.mimeType??'');if(m==='application/vnd.google-apps.document')return{supported:true,text:await gtext(token,`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}/export?mimeType=${encodeURIComponent('text/plain')}`)};if(m==='application/vnd.google-apps.spreadsheet')return{supported:true,text:await sheet(token,id)};if(/^(text\/|application\/(json|csv|xml))/i.test(m))return{supported:true,text:await gtext(token,`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`)};return{supported:false,text:`Archivo no extraído automáticamente. Tipo: ${m}. Revisión manual requerida.`};}
function seedTitle(t:string){return t.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(?:19|20)\d{2}[-/.]\d{1,2}[-/.]\d{1,2}\b/g,' ').replace(/\b(?:semana|checkin|check-in|seguimiento|cuestionario|formulario|informe|analitica|plan|entrenamiento|nutricion|apd|sport|\d+)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()||t.toLowerCase();}
async function drive(token:string,since:Date){const q=encodeURIComponent(`modifiedTime > '${since.toISOString()}' and trashed = false`),fields=encodeURIComponent('files(id,name,mimeType,modifiedTime,version,description,webViewLink,parents,size)');const l=await gjson<any>(token,`https://www.googleapis.com/drive/v3/files?pageSize=100&orderBy=modifiedTime&spaces=drive&supportsAllDrives=true&includeItemsFromAllDrives=true&q=${q}&fields=${fields}`);const res:SourceDoc[]=[];for(const f of l.files??[]){const title=String(f.name??'Archivo'),description=String(f.description??'');const c=await driveContent(token,f);const text=clean(`${title}\n${description}\n${c.text}`);if(!relevant(text))continue;res.push({sourceType:'DRIVE',id:String(f.id),revision:String(f.version??f.modifiedTime??''),modifiedAt:String(f.modifiedTime??now()),title,text,mimeType:String(f.mimeType??''),clientSeed:seedTitle(title),metadata:{webViewLink:f.webViewLink,parents:f.parents,supportedExtraction:c.supported}});}return res;}

function parseAnalysis(raw:string):Analysis{const c=raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/i,''),a=c.indexOf('{'),b=c.lastIndexOf('}');if(a<0||b<a)throw new Error('Workers AI no devolvió JSON');const j=JSON.parse(c.slice(a,b+1));const material=['Cuestionario','Check-in','Formulario','Analítica','Informe','Datos'].includes(String(j.material_type))?String(j.material_type):'Datos';return{material_type:material,objective:clean(String(j.objective??'')),summary:clean(String(j.summary??'')),changes:arr(j.changes),improved:arr(j.improved),worsened:arr(j.worsened),maintained:arr(j.maintained),red_flags:arr(j.red_flags),pending_questions:arr(j.pending_questions),hypotheses:arr(j.hypotheses),training:arr(j.training),nutrition_fueling:arr(j.nutrition_fueling),recovery:arr(j.recovery),metrics:arr(j.metrics),reply_message:clean(String(j.reply_message??'')),priority_score_0_100:Math.max(0,Math.min(100,Number(j.priority_score_0_100??0)||0)),review_points:arr(j.review_points),minutes_saved:Math.max(1,Math.min(120,Number(j.minutes_saved??10)||10))};}
async function usage(env:Env){const d=now().slice(0,10),r=await env.DB.prepare('SELECT ai_calls FROM daily_usage WHERE day=?').bind(d).first<{ai_calls:number}>();return Number(r?.ai_calls??0);}
async function ai(env:Env,s:SourceDoc,previous:Analysis|null){if(await usage(env)>=int(env.MAX_AI_CALLS_PER_DAY,12))throw new Error('AI_DAILY_BUDGET_REACHED');const prior=previous?JSON.stringify({summary:previous.summary,changes:previous.changes,red_flags:previous.red_flags,metrics:previous.metrics,training:previous.training,nutrition_fueling:previous.nutrition_fueling,recovery:previous.recovery}):'Sin seguimiento anterior';const prompt=`Analiza este seguimiento deportivo para revisión humana APD SPORT. No diagnostiques, no inventes y compara con el anterior. Devuelve SOLO JSON válido con: material_type, objective, summary, changes[], improved[], worsened[], maintained[], red_flags[], pending_questions[], hypotheses[], training[], nutrition_fueling[], recovery[], metrics[], reply_message, priority_score_0_100, review_points[], minutes_saved.\nANTERIOR:${prior}\nACTUAL:${s.title}\n${s.text.slice(0,int(env.MAX_SOURCE_CHARS,15000))}`;const r=await env.AI.run(env.AI_MODEL||'@cf/meta/llama-3.1-8b-instruct',{messages:[{role:'system',content:'Responde solo JSON válido en español de España.'},{role:'user',content:prompt}],temperature:0.1,max_tokens:1200});await env.DB.prepare(`INSERT INTO daily_usage(day,ai_calls,items_processed,updated_at) VALUES(?,1,0,?) ON CONFLICT(day) DO UPDATE SET ai_calls=ai_calls+1,updated_at=excluded.updated_at`).bind(now().slice(0,10),now()).run();return parseAnalysis(typeof r==='string'?r:String(r?.response??r?.result?.response??''));}
function score(s:SourceDoc,a:Analysis){let n=a.priority_score_0_100,l=s.text.toLowerCase();if(/lesi[oó]n|dolor agudo|mareo|desmayo|sangrado|dolor tor[aá]cico|fiebre/.test(l))n+=20;if(/anal[ií]tica|ferritina|hemoglobina|creatinina/.test(l))n+=10;if(/competici[oó]n|carrera|marat[oó]n|triatl[oó]n/.test(l))n+=8;if(/adherencia baja|sin dormir|insomnio/.test(l))n+=10;n+=Math.min(20,a.red_flags.length*5);return Math.max(0,Math.min(100,Math.round(n)));}
const priority=(n:number)=>n>=75?'ROJA':n>=45?'NARANJA':'VERDE';
const sec=(t:string,v:string|string[])=>`${t}\n${Array.isArray(v)?(v.length?v.map(x=>`- ${x}`).join('\n'):'- Sin datos'):(v||'Sin datos')}\n\n`;
function draft(s:SourceDoc,ref:string,a:Analysis,p:string,n:number){return `BORRADOR PRIVADO — ${ref}\n\nFuente: ${s.title}\nOrigen: ${s.sourceType}\nModificado: ${s.modifiedAt}\nEstado: PENDIENTE DE REVISIÓN HUMANA\nPrioridad: ${p} (${n}/100)\n\n${sec('Resumen',a.summary)}${sec('Objetivo',a.objective)}${sec('Qué ha cambiado',a.changes)}${sec('Qué mejora',a.improved)}${sec('Qué empeora',a.worsened)}${sec('Qué se mantiene',a.maintained)}${sec('Banderas rojas',a.red_flags)}${sec('Preguntas pendientes',a.pending_questions)}${sec('Hipótesis no diagnósticas',a.hypotheses)}${sec('Entrenamiento',a.training)}${sec('Nutrición y fueling',a.nutrition_fueling)}${sec('Recuperación',a.recovery)}${sec('Métricas',a.metrics)}${sec('Mensaje propuesto',a.reply_message)}AVISO: Documento interno. No enviar automáticamente al cliente.`;}

async function googleDoc(env:Env,token:string,title:string,body:string){const f=await gjson<any>(token,'https://www.googleapis.com/drive/v3/files?fields=id,webViewLink',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:title,mimeType:'application/vnd.google-apps.document',parents:[env.GOOGLE_DRAFTS_FOLDER_ID]})});await gjson<any>(token,`https://docs.googleapis.com/v1/documents/${encodeURIComponent(f.id)}:batchUpdate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requests:[{insertText:{location:{index:1},text:body}}]})});return{id:String(f.id),url:String(f.webViewLink??`https://docs.google.com/document/d/${f.id}/edit`)};}
async function slack(env:Env,ref:string,a:Analysis,p:string,n:number,url:string){const text=`*${ref}* · ${a.material_type}\n*Estado:* PENDIENTE · *Prioridad:* ${p} (${n}/100)\n*Revisar:* ${redact(a.review_points.join('; ')||'Revisión general').slice(0,1800)}\n*Tiempo estimado ahorrado:* ${a.minutes_saved} min\n<${url}|Abrir borrador protegido>\n\n✅ aprobar · 🔁 revisar · ⏸ posponer · ❌ descartar`;const r=await fetch('https://slack.com/api/chat.postMessage',{method:'POST',headers:{authorization:`Bearer ${env.SLACK_BOT_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({channel:env.SLACK_CHANNEL_ID,text,unfurl_links:false,unfurl_media:false})});const j=await r.json<any>();if(!r.ok||!j.ok)throw new Error(`Slack: ${JSON.stringify(j)}`);return{channel:String(j.channel??env.SLACK_CHANNEL_ID),ts:String(j.ts)};}
async function notion(env:Env,ref:string,s:SourceDoc,a:Analysis,p:string,n:number,url:string,keyHash:string){const properties:any={Caso:{title:[{text:{content:ref}}]},'Cliente ID':{rich_text:[{text:{content:ref}}]},Material:{select:{name:a.material_type}},Estado:{select:{name:'PENDIENTE'}},Prioridad:{select:{name:p}},Score:{number:n},Origen:{select:{name:s.sourceType}},Modificado:{date:{start:s.modifiedAt}},Creado:{date:{start:now()}},Borrador:{url},'Puntos a revisar':{rich_text:[{text:{content:redact(a.review_points.join('; ')).slice(0,1900)}}]},'Minutos ahorrados':{number:a.minutes_saved},'Contiene sensible':{checkbox:false},'ID externo hash':{rich_text:[{text:{content:keyHash}}]}};const r=await fetch('https://api.notion.com/v1/pages',{method:'POST',headers:{authorization:`Bearer ${env.NOTION_TOKEN}`,'notion-version':env.NOTION_VERSION||'2025-09-03','content-type':'application/json'},body:JSON.stringify({parent:{type:'data_source_id',data_source_id:env.NOTION_DATA_SOURCE_ID},properties})});const j=await r.json<any>();if(!r.ok)throw new Error(`Notion: ${JSON.stringify(j)}`);return String(j.id??'');}
async function notionStatus(env:Env,id:string,d:Decision){if(!id)return;const r=await fetch(`https://api.notion.com/v1/pages/${encodeURIComponent(id)}`,{method:'PATCH',headers:{authorization:`Bearer ${env.NOTION_TOKEN}`,'notion-version':env.NOTION_VERSION||'2025-09-03','content-type':'application/json'},body:JSON.stringify({properties:{Estado:{select:{name:d}}}})});if(!r.ok)throw new Error(await r.text());}

async function checkpoint(env:Env,k:string){const r=await env.DB.prepare('SELECT value FROM checkpoints WHERE key=?').bind(k).first<{value:string}>();return r?.value??null;}
async function setCheckpoint(env:Env,k:string,v:string){await env.DB.prepare(`INSERT INTO checkpoints(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).bind(k,v,now()).run();}
async function previous(env:Env,ref:string,key:string){const r=await env.DB.prepare('SELECT source_key,analysis_json FROM sources WHERE client_ref=? AND source_key<>? ORDER BY processed_at DESC LIMIT 1').bind(ref,key).first<{source_key:string;analysis_json:string}>();if(!r)return null;try{return{key:r.source_key,a:JSON.parse(r.analysis_json) as Analysis};}catch{return null;}}

async function handle(env:Env,token:string,s:SourceDoc){const key=`${s.sourceType}:${s.id}`,hash=await sha(s.text),old=await env.DB.prepare('SELECT revision,content_hash FROM sources WHERE source_key=?').bind(key).first<{revision:string;content_hash:string}>();if(old&&old.revision===s.revision&&old.content_hash===hash)return'skipped';const ref=`CP-${(await sha(s.clientSeed)).slice(0,8).toUpperCase()}`,prev=await previous(env,ref,key),a=await ai(env,s,prev?.a??null),n=score(s,a),p=priority(n),at=now(),dry=bool(env.DRY_RUN,true);let fileId='',url='SIMULACIÓN: no se ha creado documento',channel='',ts='',notionId='';if(!dry){const d=await googleDoc(env,token,`${ref} — ${a.material_type} — ${at.slice(0,10)}`,draft(s,ref,a,p,n));fileId=d.id;url=d.url;const sm=await slack(env,ref,a,p,n,url);channel=sm.channel;ts=sm.ts;notionId=await notion(env,ref,s,a,p,n,url,await sha(key));}await env.DB.prepare(`INSERT INTO sources(source_key,source_type,external_id,revision,modified_at,content_hash,title_hash,mime_type,client_ref,status,priority,priority_score,material_type,draft_file_id,draft_url,slack_channel,slack_ts,notion_page_id,analysis_json,metadata_json,previous_source_key,processed_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source_key) DO UPDATE SET revision=excluded.revision,modified_at=excluded.modified_at,content_hash=excluded.content_hash,title_hash=excluded.title_hash,mime_type=excluded.mime_type,client_ref=excluded.client_ref,status=excluded.status,priority=excluded.priority,priority_score=excluded.priority_score,material_type=excluded.material_type,draft_file_id=excluded.draft_file_id,draft_url=excluded.draft_url,slack_channel=excluded.slack_channel,slack_ts=excluded.slack_ts,notion_page_id=excluded.notion_page_id,analysis_json=excluded.analysis_json,metadata_json=excluded.metadata_json,previous_source_key=excluded.previous_source_key,processed_at=excluded.processed_at,updated_at=excluded.updated_at`).bind(key,s.sourceType,s.id,s.revision,s.modifiedAt,hash,await sha(s.title),s.mimeType,ref,dry?'SIMULADO':'PENDIENTE',p,n,a.material_type,fileId,url,channel,ts,notionId,JSON.stringify(a),JSON.stringify(s.metadata),prev?.key??null,at,at).run();await env.DB.prepare(`INSERT INTO daily_usage(day,ai_calls,items_processed,updated_at) VALUES(?,0,1,?) ON CONFLICT(day) DO UPDATE SET items_processed=items_processed+1,updated_at=excluded.updated_at`).bind(at.slice(0,10),at).run();return'processed';}

async function run(env:Env,trigger:string){const started=now(),ins=await env.DB.prepare('INSERT INTO runs(trigger_type,started_at,status) VALUES(?,?,?)').bind(trigger,started,'RUNNING').run(),id=Number(ins.meta.last_row_id);let discovered=0,processed=0,skipped=0,failed=0;const errors:string[]=[];try{const cp=await checkpoint(env,'last_successful_scan'),init=await checkpoint(env,'system_initialized_at'),since=cp?new Date(cp):init?new Date(init):new Date(Date.now()-int(env.LOOKBACK_MINUTES,90)*60000),token=await accessToken(env),[gm,dr]=await Promise.all([gmail(env,token,since),drive(token,since)]),items=[...gm,...dr].sort((a,b)=>a.modifiedAt.localeCompare(b.modifiedAt)).slice(0,int(env.MAX_ITEMS_PER_RUN,3));discovered=items.length;for(const s of items){try{(await handle(env,token,s))==='processed'?processed++:skipped++;}catch(e){failed++;errors.push(`${s.sourceType}:${s.id}: ${e instanceof Error?e.message:String(e)}`);}}if(!failed)await setCheckpoint(env,'last_successful_scan',started);await env.DB.prepare('UPDATE runs SET finished_at=?,status=?,discovered=?,processed=?,skipped=?,failed=?,detail=? WHERE id=?').bind(now(),failed?'PARTIAL':'SUCCESS',discovered,processed,skipped,failed,JSON.stringify(errors),id).run();return{id,status:failed?'PARTIAL':'SUCCESS',discovered,processed,skipped,failed,dryRun:bool(env.DRY_RUN,true),errors};}catch(e){await env.DB.prepare("UPDATE runs SET finished_at=?,status='FAILED',detail=? WHERE id=?").bind(now(),e instanceof Error?e.message:String(e),id).run();throw e;}}

async function verifySlack(req:Request,env:Env,body:string){const ts=req.headers.get('x-slack-request-timestamp')??'',sig=req.headers.get('x-slack-signature')??'';if(!ts||!sig||Math.abs(Math.floor(Date.now()/1000)-Number(ts))>300)return false;const key=await crypto.subtle.importKey('raw',enc.encode(env.SLACK_SIGNING_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']),signed=await crypto.subtle.sign('HMAC',key,enc.encode(`v0:${ts}:${body}`)),hex=[...new Uint8Array(signed)].map(x=>x.toString(16).padStart(2,'0')).join('');return equal(`v0=${hex}`,sig);}
async function slackEvent(req:Request,env:Env){const body=await req.text();if(!(await verifySlack(req,env,body)))return out({ok:false,error:'invalid_signature'},401);const p=JSON.parse(body) as any;if(p.type==='url_verification')return out({challenge:p.challenge});if(p.event_id){const r=await env.DB.prepare('INSERT OR IGNORE INTO event_receipts(event_id,event_type,received_at) VALUES(?,?,?)').bind(String(p.event_id),String(p.event?.type??p.type),now()).run();if(!r.meta.changes)return out({ok:true,duplicate:true});}const e=p.event;if(e?.type!=='reaction_added'||e.item?.type!=='message')return out({ok:true,ignored:true});const d=REACTIONS[String(e.reaction)];if(!d)return out({ok:true,ignored:true});const s=await env.DB.prepare('SELECT source_key,notion_page_id FROM sources WHERE slack_channel=? AND slack_ts=? LIMIT 1').bind(String(e.item.channel),String(e.item.ts)).first<{source_key:string;notion_page_id:string}>();if(!s)return out({ok:true,ignored:true,reason:'message_not_managed'});await env.DB.batch([env.DB.prepare('INSERT INTO decisions(source_key,decision,slack_user_id,slack_reaction,decided_at) VALUES(?,?,?,?,?)').bind(s.source_key,d,String(e.user??''),String(e.reaction),now()),env.DB.prepare('UPDATE sources SET status=?,updated_at=? WHERE source_key=?').bind(d,now(),s.source_key)]);if(env.NOTION_TOKEN&&s.notion_page_id)await notionStatus(env,s.notion_page_id,d);return out({ok:true,decision:d});}
async function status(env:Env){return{ok:true,service:'apd-client-agent',dryRun:bool(env.DRY_RUN,true),checkpoint:await checkpoint(env,'last_successful_scan'),latestRun:await env.DB.prepare('SELECT * FROM runs ORDER BY id DESC LIMIT 1').first(),sourceCounts:(await env.DB.prepare('SELECT status,COUNT(*) total FROM sources GROUP BY status').all()).results};}

export default {
  async scheduled(_c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(run(env,'CRON').then(console.log).catch(console.error));},
  async fetch(req:Request,env:Env,ctx:ExecutionContext){const u=new URL(req.url);if(req.method==='GET'&&u.pathname==='/health')return out(await status(env));if(req.method==='POST'&&u.pathname==='/slack/events')return slackEvent(req,env);if(req.method==='POST'&&u.pathname==='/admin/run'){const auth=req.headers.get('authorization')??'';if(!env.ADMIN_TOKEN||!equal(auth,`Bearer ${env.ADMIN_TOKEN}`))return out({ok:false,error:'unauthorized'},401);const p=run(env,'MANUAL');ctx.waitUntil(p);return out(await p);}return out({ok:true,service:'apd-client-agent',endpoints:['/health','/admin/run','/slack/events']});}
};
